Repository prgrms-be-devcourse/NBE2-3-3-team6, pull requests merged in 2025-01, with the labels that each got.

#5 User 엔티티 마이그레이션
  build.gradle
  settings.gradle
  src/main/java/com/redbox/domain/user/entity/User.java
  src/main/java/com/redbox/domain/user/entity/User.kt
Labels: 🔨 Refactor

#6 Article 엔티티 마이그레이션
  src/main/java/com/redbox/domain/article/entity/Article.java
  src/main/java/com/redbox/domain/article/entity/Article.kt
Labels: 🔨 Refactor

#9 Redcard 엔티티 마이그레이션
  src/main/java/com/redbox/domain/redcard/entity/Redcard.java
  src/main/java/com/redbox/domain/redcard/entity/Redcard.kt
Labels: 🔨 Refactor

#10 Notice 엔티티 마이그레이션
  src/main/java/com/redbox/domain/notice/entity/Notice.java
  src/main/java/com/redbox/domain/notice/entity/Notice.kt
Labels: 🔨 Refactor

#11 AttachFile 엔티티 마이그레이션
  src/main/java/com/redbox/domain/attach/entity/AttachFile.java
  src/main/java/com/redbox/domain/attach/entity/AttachFile.kt
Labels: 🔨 Refactor

#19 Redcard 엔티티 수정
  src/main/java/com/redbox/domain/redcard/entity/Redcard.kt
Labels: 🔨 Refactor

#20 User domain migration
  build.gradle
  settings.gradle
  src/main/java/com/redbox/domain/user/dto/CheckUserRequest.java
  src/main/java/com/redbox/domain/user/dto/CheckUserRequest.kt
  src/main/java/com/redbox/domain/user/dto/CheckUserResponse.java
  src/main/java/com/redbox/domain/user/dto/CheckUserResponse.kt
  src/main/java/com/redbox/domain/user/dto/DonationResponse.java
  src/main/java/com/redbox/domain/user/dto/DonationResponse.kt
  src/main/java/com/redbox/domain/user/dto/DropInfoRequest.java
  src/main/java/com/redbox/domain/user/dto/DropInfoRequest.kt
  src/main/java/com/redbox/domain/user/dto/FindIdRequest.java
  src/main/java/com/redbox/domain/user/dto/FindIdRequest.kt
  src/main/java/com/redbox/domain/user/dto/FindIdResponse.java
  src/main/java/com/redbox/domain/user/dto/FindIdResponse.kt
  src/main/java/com/redbox/domain/user/dto/LoginRequest.java
  src/main/java/com/redbox/domain/user/dto/LoginRequest.kt
  src/main/java/com/redbox/domain/user/dto/ReceptionResponse.java
  src/main/java/com/redbox/domain/user/dto/ReceptionResponse.kt
  src/main/java/com/redbox/domain/user/dto/RedcardResponse.java
  src/main/java/com/redbox/domain/user/dto/RedcardResponse.kt
  src/main/java/com/redbox/domain/user/dto/ResetPasswordRequest.java
  src/main/java/com/redbox/domain/user/dto/ResetPasswordRequest.kt
  src/main/java/com/redbox/domain/user/dto/SignupRequest.java
  src/main/java/com/redbox/domain/user/dto/SignupRequest.kt
  src/main/java/com/redbox/domain/user/dto/SignupResponse.java
  src/main/java/com/redbox/domain/user/dto/SignupResponse.kt
  src/main/java/com/redbox/domain/user/dto/UpdatePasswordRequest.java
  src/main/java/com/redbox/domain/user/dto/UpdatePasswordRequest.kt
  src/main/java/com/redbox/domain/user/dto/UpdateRedcardStatusRequest.java
  src/main/java/com/redbox/domain/user/dto/UpdateRedcardStatusRequest.kt
  src/main/java/com/redbox/domain/user/dto/UpdateUserInfoRequest.java
  src/main/java/com/redbox/domain/user/dto/UpdateUserInfoRequest.kt
  src/main/java/com/redbox/domain/user/dto/UserDTO.java
  src/main/java/com/redbox/domain/user/dto/UserDTO.kt
  src/main/java/com/redbox/domain/user/dto/UserInfoResponse.java
  src/main/java/com/redbox/domain/user/dto/UserInfoResponse.kt
  src/main/java/com/redbox/domain/user/dto/ValidateVerificationCodeRequest.java
  src/main/java/com/redbox/domain/user/dto/ValidateVerificationCodeRequest.kt
  src/main/java/com/redbox/domain/user/dto/VerificationCodeRequest.java
  src/main/java/com/redbox/domain/user/dto/VerificationCodeRequest.kt
  src/main/java/com/redbox/domain/user/entity/Gender.java
  src/main/java/com/redbox/domain/user/entity/Gender.kt
  src/main/java/com/redbox/domain/user/entity/RoleType.java
  src/main/java/com/redbox/domain/user/entity/RoleType.kt
  src/main/java/com/redbox/domain/user/entity/Status.java
  src/main/java/com/redbox/domain/user/entity/Status.kt
  src/main/java/com/redbox/domain/user/entity/User.java
  src/main/java/com/redbox/domain/user/entity/User.kt
Labels: 🔨 Refactor

#22 user domain
  src/main/java/com/redbox/domain/user/dto/CheckUserRequest.java
  src/main/java/com/redbox/domain/user/dto/CheckUserRequest.kt
  src/main/java/com/redbox/domain/user/dto/CheckUserResponse.java
  src/main/java/com/redbox/domain/user/dto/CheckUserResponse.kt
  src/main/java/com/redbox/domain/user/dto/DonationResponse.java
  src/main/java/com/redbox/domain/user/dto/DonationResponse.kt
  src/main/java/com/redbox/domain/user/dto/DropInfoRequest.java
  src/main/java/com/redbox/domain/user/dto/DropInfoRequest.kt
  src/main/java/com/redbox/domain/user/dto/FindIdRequest.java
  src/main/java/com/redbox/domain/user/dto/FindIdRequest.kt
  src/main/java/com/redbox/domain/user/dto/FindIdResponse.java
  src/main/java/com/redbox/domain/user/dto/FindIdResponse.kt
  src/main/java/com/redbox/domain/user/dto/LoginRequest.java
  src/main/java/com/redbox/domain/user/dto/LoginRequest.kt
  src/main/java/com/redbox/domain/user/dto/ReceptionResponse.java
  src/main/java/com/redbox/domain/user/dto/ReceptionResponse.kt
  src/main/java/com/redbox/domain/user/dto/RedcardResponse.java
  src/main/java/com/redbox/domain/user/dto/RedcardResponse.kt
  src/main/java/com/redbox/domain/user/dto/ResetPasswordRequest.java
  src/main/java/com/redbox/domain/user/dto/ResetPasswordRequest.kt
  src/main/java/com/redbox/domain/user/dto/SignupRequest.java
  src/main/java/com/redbox/domain/user/dto/SignupRequest.kt
  src/main/java/com/redbox/domain/user/dto/SignupResponse.java
  src/main/java/com/redbox/domain/user/dto/SignupResponse.kt
  src/main/java/com/redbox/domain/user/dto/UpdatePasswordRequest.java
  src/main/java/com/redbox/domain/user/dto/UpdatePasswordRequest.kt
  src/main/java/com/redbox/domain/user/dto/UpdateRedcardStatusRequest.java
  src/main/java/com/redbox/domain/user/dto/UpdateRedcardStatusRequest.kt
  src/main/java/com/redbox/domain/user/dto/UpdateUserInfoRequest.java
  src/main/java/com/redbox/domain/user/dto/UpdateUserInfoRequest.kt
  src/main/java/com/redbox/domain/user/dto/UserDTO.java
  src/main/java/com/redbox/domain/user/dto/UserDTO.kt
  src/main/java/com/redbox/domain/user/dto/UserInfoResponse.java
  src/main/java/com/redbox/domain/user/dto/UserInfoResponse.kt
  src/main/java/com/redbox/domain/user/dto/ValidateVerificationCodeRequest.java
  src/main/java/com/redbox/domain/user/dto/ValidateVerificationCodeRequest.kt
  src/main/java/com/redbox/domain/user/dto/VerificationCodeRequest.java
  src/main/java/com/redbox/domain/user/dto/VerificationCodeRequest.kt
  src/main/java/com/redbox/domain/user/entity/Gender.java
  src/main/java/com/redbox/domain/user/entity/Gender.kt
  src/main/java/com/redbox/domain/user/entity/RoleType.java
  src/main/java/com/redbox/domain/user/entity/RoleType.kt
  src/main/java/com/redbox/domain/user/entity/Status.java
  src/main/java/com/redbox/domain/user/entity/Status.kt
Labels: 🔨 Refactor

#28 refactor: 글로벌 Entity 클래스 코틀린 마이그레이션
  migration/src/main/kotlin/com/redbox/global/entity/BaseEntity.kt
  migration/src/main/kotlin/com/redbox/global/entity/BaseTimeEntity.kt
  migration/src/main/kotlin/com/redbox/global/entity/PageResponse.kt
Labels: 🔨 Refactor

#29 Refactor/#25 global exception migration
  migration/src/main/kotlin/com/redbox/global/exception/AuthException.kt
  migration/src/main/kotlin/com/redbox/global/exception/BusinessException.kt
  migration/src/main/kotlin/com/redbox/global/exception/ErrorCode.kt
  migration/src/main/kotlin/com/redbox/global/exception/ErrorResponse.kt
  migration/src/main/kotlin/com/redbox/global/exception/GlobalExceptionHandler.kt
Labels: 🔨 Refactor

#30 Util 패키지 마이그레이션
  migration/src/main/kotlin/com/redbox/global/exception/BusinessException.kt
  migration/src/main/kotlin/com/redbox/global/util/FileUtils.kt
  migration/src/main/kotlin/com/redbox/global/util/RandomCodeGenerator.kt
  migration/src/main/kotlin/com/redbox/global/util/email/EmailCreationException.kt
  migration/src/main/kotlin/com/redbox/global/util/email/EmailSendException.kt
  migration/src/main/kotlin/com/redbox/global/util/email/EmailSender.kt
  migration/src/main/kotlin/com/redbox/global/util/error/ErrorResponseUtil.kt
Labels: 🔨 Refactor

#35 User 인증번호 메일 발송 기능 마이그레이션
  migration/src/main/kotlin/com/redbox/domain/user/controller/UserController.kt
  migration/src/main/kotlin/com/redbox/domain/user/dto/VerificationCodeRequest.kt
  migration/src/main/kotlin/com/redbox/domain/user/entity/Gender.kt
  migration/src/main/kotlin/com/redbox/domain/user/entity/RoleType.kt
  migration/src/main/kotlin/com/redbox/domain/user/entity/Status.kt
  migration/src/main/kotlin/com/redbox/domain/user/entity/User.kt
  migration/src/main/kotlin/com/redbox/domain/user/exception/DuplicateEmailException.kt
  migration/src/main/kotlin/com/redbox/domain/user/exception/EmptyPasswordException.kt
  migration/src/main/kotlin/com/redbox/domain/user/repository/EmailVerificationCodeRepository.kt
  migration/src/main/kotlin/com/redbox/domain/user/repository/UserRepository.kt
  migration/src/main/kotlin/com/redbox/domain/user/service/UserService.kt
  migration/src/main/kotlin/com/redbox/global/config/RedisConfig.kt
  migration/src/main/kotlin/com/redbox/global/config/SecurityConfig.kt
  migration/src/main/resources/templates/verification-code-email.html
Labels: 🔨 Refactor

#37 Refactor/#33 redcard register migration
  migration/build.gradle.kts
  migration/src/main/kotlin/com/redbox/domain/redcard/dto/RegisterRedcardRequest.kt
  migration/src/main/kotlin/com/redbox/domain/redcard/entity/OwnerType.kt
  migration/src/main/kotlin/com/redbox/domain/redcard/entity/Redcard.kt
  migration/src/main/kotlin/com/redbox/domain/redcard/entity/RedcardStatus.kt
  migration/src/main/kotlin/com/redbox/domain/redcard/exception/DuplicateSerialNumberException.kt
  migration/src/main/kotlin/com/redbox/domain/redcard/repository/RedcardRepository.kt
  migration/src/main/kotlin/com/redbox/domain/redcard/service/RedcardService.kt
  migration/src/test/kotlin/com/redbox/domain/redcard/service/RedcardServiceTest.kt
Labels: 🔨 Refactor, ✅ Test

#38 User 인증번호 검증 기능 마이그레이션
  migration/src/main/kotlin/com/redbox/domain/user/controller/UserController.kt
  migration/src/main/kotlin/com/redbox/domain/user/dto/ValidateVerificationCodeRequest.kt
  migration/src/main/kotlin/com/redbox/domain/user/repository/EmailVerificationCodeRepository.kt
  migration/src/main/kotlin/com/redbox/domain/user/service/UserService.kt
Labels: 🔨 Refactor

#42 User 회원가입 기능 마이그레이션
  migration/src/main/kotlin/com/redbox/domain/user/controller/UserController.kt
  migration/src/main/kotlin/com/redbox/domain/user/dto/SignupRequest.kt
  migration/src/main/kotlin/com/redbox/domain/user/dto/SignupResponse.kt
  migration/src/main/kotlin/com/redbox/domain/user/entity/User.kt
  migration/src/main/kotlin/com/redbox/domain/user/exception/EmailNotVerifiedException.kt
  migration/src/main/kotlin/com/redbox/domain/user/service/UserService.kt
Labels: 🔨 Refactor

#43 Funding 등록 기능 마이그레이션
  migration/src/main/kotlin/com/redbox/domain/community/funding/controller/FundingController.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/dto/Filter.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/dto/FundingDetailResponse.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/dto/FundingFilter.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/dto/FundingWriteRequest.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/entity/Funding.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/entity/FundingStatus.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/entity/Priority.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/exception/FundingNotFoundException.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/exception/UnauthorizedAccessException.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/exception/UserNotFoundException.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/repository/FundingRepository.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/repository/FundingRepositoryCustom.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/service/FundingService.kt
Labels: 🔨 Refactor

#46 User 비밀번호 초기화 기능 마이그레이션
  migration/src/main/kotlin/com/redbox/domain/user/controller/UserController.kt
  migration/src/main/kotlin/com/redbox/domain/user/dto/ResetPasswordRequest.kt
  migration/src/main/kotlin/com/redbox/domain/user/repository/UserRepository.kt
  migration/src/main/kotlin/com/redbox/domain/user/service/UserService.kt
  migration/src/main/resources/templates/temp-password-email.html
Labels: 🔨 Refactor

#51 test: 헌혈증 조회 기능 테스트 추가
  migration/src/main/kotlin/com/redbox/domain/redcard/repository/RedcardRepository.kt
  migration/src/main/kotlin/com/redbox/domain/redcard/service/RedcardService.kt
  migration/src/test/kotlin/com/redbox/domain/redcard/service/RedcardServiceTest.kt
Labels: ✅ Test

#54 다른 도메인에서 사용되는 UserService 기능 퍼사드패턴 적용
  migration/src/main/kotlin/com/redbox/domain/user/facade/UserFacade.kt
  migration/src/main/kotlin/com/redbox/domain/user/repository/UserRepository.kt
  migration/src/main/kotlin/com/redbox/domain/user/service/UserService.kt
  migration/src/main/kotlin/com/redbox/global/auth/dto/CustomUserDetails.kt
Labels: ✨ Feature, 🔨 Refactor

#55 Refactor/#53 update redcards owner migration
  migration/src/main/kotlin/com/redbox/domain/redcard/exception/RedcardNotFoundException.kt
  migration/src/main/kotlin/com/redbox/domain/redcard/service/RedcardService.kt
Labels: 🔨 Refactor

#57 헌혈증 등록 기능 마이그레이션
  migration/src/main/kotlin/com/redbox/domain/redcard/facade/RedcardFacade.kt
  migration/src/main/kotlin/com/redbox/domain/redcard/service/RedcardService.kt
  migration/src/main/kotlin/com/redbox/domain/user/controller/UserController.kt
  migration/src/main/kotlin/com/redbox/domain/user/facade/UserFacade.kt
  migration/src/main/kotlin/com/redbox/domain/user/service/UserService.kt
  migration/src/main/kotlin/com/redbox/global/auth/service/AuthenticationService.kt
Labels: ✨ Feature, 🔨 Refactor

#59 User 회원 탈퇴 기능 마이그레이션
  migration/src/main/kotlin/com/redbox/domain/user/controller/UserController.kt
  migration/src/main/kotlin/com/redbox/domain/user/dto/DropInfoRequest.kt
  migration/src/main/kotlin/com/redbox/domain/user/exception/PasswordMismatchException.kt
  migration/src/main/kotlin/com/redbox/domain/user/service/UserService.kt
  migration/src/main/kotlin/com/redbox/global/exception/AuthException.kt
Labels: 🔨 Refactor

#61 Refactor/#56 update redcard status migration
  migration/src/main/kotlin/com/redbox/domain/redcard/exception/InvalidRedcardStatusException.kt
  migration/src/main/kotlin/com/redbox/domain/redcard/exception/PendingRedcardException.kt
  migration/src/main/kotlin/com/redbox/domain/redcard/exception/RedcardNotBelongException.kt
  migration/src/main/kotlin/com/redbox/domain/redcard/repository/RedcardRepository.kt
  migration/src/main/kotlin/com/redbox/domain/redcard/service/RedcardService.kt
  migration/src/main/kotlin/com/redbox/domain/user/dto/UpdateRedcardStatusRequest.kt
Labels: 🔨 Refactor

#62 User 내 정보 조회, 수정, 비밀번호 수정 마이그레이션
  migration/src/main/kotlin/com/redbox/domain/user/controller/UserController.kt
  migration/src/main/kotlin/com/redbox/domain/user/dto/UpdatePasswordRequest.kt
  migration/src/main/kotlin/com/redbox/domain/user/dto/UpdateUserInfoRequest.kt
  migration/src/main/kotlin/com/redbox/domain/user/dto/UserInfoResponse.kt
  migration/src/main/kotlin/com/redbox/domain/user/exception/PasswordNotMatchException.kt
  migration/src/main/kotlin/com/redbox/domain/user/service/UserService.kt
Labels: 🔨 Refactor

#67 refactor: Redcard 엔티티 클래스 수정
  migration/src/main/kotlin/com/redbox/domain/redcard/entity/Redcard.kt
Labels: 🔨 Refactor

#71 refactor: 헌혈증 소유자 및 소유자 타입 변경 기능 마이그레이션
  migration/src/main/kotlin/com/redbox/domain/redcard/service/RedcardService.kt
Labels: 🔨 Refactor

#73 User 내 헌혈증 조회, 헌혈증 상태 변경
  migration/src/main/kotlin/com/redbox/domain/redcard/dto/RedcardResponse.kt
  migration/src/main/kotlin/com/redbox/domain/redcard/dto/UpdateRedcardStatusRequest.kt
  migration/src/main/kotlin/com/redbox/domain/redcard/facade/RedcardFacade.kt
  migration/src/main/kotlin/com/redbox/domain/redcard/repository/RedcardRepository.kt
  migration/src/main/kotlin/com/redbox/domain/redcard/service/RedcardService.kt
  migration/src/main/kotlin/com/redbox/domain/user/controller/UserController.kt
  migration/src/main/kotlin/com/redbox/domain/user/dto/UpdateRedcardStatusRequest.kt
  migration/src/main/kotlin/com/redbox/domain/user/service/UserService.kt
Labels: 🔨 Refactor

#76 refactor: 헌혈증 상태를 PENDING으로 변경하는 기능 마이그레이션
  migration/src/main/kotlin/com/redbox/domain/redcard/service/RedcardService.kt
Labels: 🔨 Refactor

#78 refactor: 헌혈증 상태를 AVAILABLE로 변경하는 기능 마이그레이션
  migration/src/main/kotlin/com/redbox/domain/redcard/service/RedcardService.kt
Labels: 🔨 Refactor

#84 refactor: Funding Like 마이그레이션
  migration/src/main/kotlin/com/redbox/domain/community/funding/controller/FundingController.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/dto/LikeResponse.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/entity/Like.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/repository/LikeRepository.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/service/FundingService.kt
Labels: 🔨 Refactor

#87 Attach 파일 업로드 마이그레이션
  migration/src/main/kotlin/com/redbox/domain/community/attach/dto/AttachFileResponse.kt
  migration/src/main/kotlin/com/redbox/domain/community/attach/entity/AttachFile.kt
  migration/src/main/kotlin/com/redbox/domain/community/attach/entity/Category.kt
  migration/src/main/kotlin/com/redbox/domain/community/attach/exception/AttachFileNotFoundException.kt
  migration/src/main/kotlin/com/redbox/domain/community/attach/exception/FileNotBelongException.kt
  migration/src/main/kotlin/com/redbox/domain/community/attach/exception/NullAttachFileException.kt
  migration/src/main/kotlin/com/redbox/domain/community/attach/repository/AttachFileRepository.kt
  migration/src/main/kotlin/com/redbox/domain/community/attach/service/AttachFileService.kt
  migration/src/main/kotlin/com/redbox/domain/community/attach/strategy/FileAttachStrategy.kt
  migration/src/main/kotlin/com/redbox/domain/community/attach/strategy/FileAttachStrategyFactory.kt
  migration/src/main/kotlin/com/redbox/domain/community/attach/strategy/FundingFileStrategy.kt
  migration/src/main/kotlin/com/redbox/global/config/S3Config.kt
  migration/src/main/kotlin/com/redbox/global/infra/s3/S3Exception.kt
  migration/src/main/kotlin/com/redbox/global/infra/s3/S3Service.kt
Labels: 🔨 Refactor

#89 refactor: Attach 파일 다운 마이그레이션
  migration/src/main/kotlin/com/redbox/domain/community/attach/service/AttachFileService.kt
Labels: 🔨 Refactor

#94 User 이메일로 유저 검색, 기부 리스트, 수혜리스트, 내가 쓴 요청 게시판 목록
  migration/src/main/kotlin/com/redbox/domain/community/funding/dto/FundingListResponse.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/entity/FundingStatus.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/facade/FundingFacade.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/repository/FundingRepository.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/service/FundingService.kt
  migration/src/main/kotlin/com/redbox/domain/donation/application/DonationService.kt
  migration/src/main/kotlin/com/redbox/domain/donation/dto/DonationListResponse.kt
  migration/src/main/kotlin/com/redbox/domain/donation/dto/ReceptionListResponse.kt
  migration/src/main/kotlin/com/redbox/domain/donation/facade/DonationFacade.kt
  migration/src/main/kotlin/com/redbox/domain/donation/repository/DonationGroupRepository.kt
  migration/src/main/kotlin/com/redbox/domain/user/controller/UserController.kt
  migration/src/main/kotlin/com/redbox/domain/user/dto/CheckUserRequest.kt
  migration/src/main/kotlin/com/redbox/domain/user/dto/CheckUserResponse.kt
  migration/src/main/kotlin/com/redbox/domain/user/service/UserService.kt
Labels: 🔨 Refactor

#96 refactor: Refresh Token 저장 기능 마이그레이션
  migration/src/main/kotlin/com/redbox/global/auth/service/RefreshTokenService.kt
Labels: 🔨 Refactor

#98 refactor: Refresh Token 존재 여부 확인 기능 마이그레이션
  migration/src/main/kotlin/com/redbox/global/auth/service/RefreshTokenService.kt
Labels: 🔨 Refactor

#100 refactor: Refresh Token 삭제 기능 코틀린으로 마이그레이션
  migration/src/main/kotlin/com/redbox/global/auth/service/RefreshTokenService.kt
Labels: 🔨 Refactor

#102 refactor: Refresh Token으로 이메일 찾기 기능 마이그레이션
  migration/src/main/kotlin/com/redbox/global/auth/service/RefreshTokenService.kt
Labels: 🔨 Refactor

#105 refactor: Funding 파일 등록 마이그레이션
  migration/src/main/kotlin/com/redbox/domain/community/funding/entity/Funding.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/service/FundingService.kt
Labels: 🔨 Refactor

#107 refactor: Funding 에서 Like 마이그레이션
  migration/src/main/kotlin/com/redbox/domain/community/funding/repository/FundingRepositoryImpl.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/service/FundingService.kt
Labels: 🔨 Refactor

#109 refactor: Funding 파일 목록 조회 마이그레이션
  migration/src/main/kotlin/com/redbox/domain/community/funding/dto/FundingDetailResponse.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/entity/Funding.kt
Labels: 🔨 Refactor

#118 refactor: JWTUtil 코틀린 마이그레이션 및 userId 타입 변환 로직 추가
  migration/src/main/kotlin/com/redbox/global/auth/util/JWTUtil.kt
Labels: 🔨 Refactor

#121 refactor: Funding 요청게시판 사용자 연결
  migration/src/main/kotlin/com/redbox/domain/community/funding/dto/FundingDetailResponse.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/dto/ListResponse.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/entity/Funding.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/repository/FundingRepository.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/service/FundingService.kt
Labels: 🔨 Refactor

#122 Refactor/#114 migrate auth refresh token validation
  migration/src/main/kotlin/com/redbox/global/auth/exception/ExpiredRefreshTokenException.kt
  migration/src/main/kotlin/com/redbox/global/auth/exception/InvalidTokenCategoryException.kt
  migration/src/main/kotlin/com/redbox/global/auth/exception/RefreshTokenNotFoundException.kt
  migration/src/main/kotlin/com/redbox/global/auth/service/ReissueService.kt
  migration/src/main/kotlin/com/redbox/global/exception/ErrorCode.kt
Labels: 🔨 Refactor

#124 Admin 요청 게시글 승인
  migration/src/main/kotlin/com/redbox/domain/community/funding/dto/AdminApproveRequest.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/exception/InvalidApproveStatusException.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/facade/FundingFacade.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/service/FundingService.kt
  migration/src/main/kotlin/com/redbox/domain/user/admin/controller/AdminController.kt
  migration/src/main/kotlin/com/redbox/domain/user/admin/service/AdminService.kt
Labels: 🔨 Refactor

#127 Admin 관련 남은 기능들
  migration/src/main/kotlin/com/redbox/domain/community/attach/repository/AttachFileRepository.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/dto/AdminDetailProjection.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/dto/AdminDetailResponse.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/facade/FundingFacade.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/repository/FundingRepository.kt
  migration/src/main/kotlin/com/redbox/domain/community/funding/service/FundingService.kt
  migration/src/main/kotlin/com/redbox/domain/donation/application/DonationService.kt
  migration/src/main/kotlin/com/redbox/domain/donation/facade/DonationFacade.kt
  migration/src/main/kotlin/com/redbox/domain/donation/repository/DonationGroupRepository.kt
  migration/src/main/kotlin/com/redbox/domain/redcard/facade/RedcardFacade.kt
  migration/src/main/kotlin/com/redbox/domain/redcard/repository/RedcardRepository.kt
  migration/src/main/kotlin/com/redbox/domain/redcard/service/RedcardService.kt
  migration/src/main/kotlin/com/redbox/domain/user/admin/controller/AdminController.kt
  migration/src/main/kotlin/com/redbox/domain/user/admin/dto/AdminStatsResponse.kt
  migration/src/main/kotlin/com/redbox/domain/user/admin/service/AdminService.kt
  migration/src/main/kotlin/com/redbox/domain/user/user/facade/UserFacade.kt
  migration/src/main/kotlin/com/redbox/domain/user/user/repository/UserRepository.kt
  migration/src/main/kotlin/com/redbox/domain/user/user/service/UserService.kt
Labels: 🔨 Refactor

#128 Refactor/#126 auth jwtfilter migration
  migration/src/main/kotlin/com/redbox/global/auth/dto/CustomUserDetails.kt
  migration/src/main/kotlin/com/redbox/global/auth/filter/JWTFilter.kt
  migration/src/main/kotlin/com/redbox/global/auth/service/AuthenticationService.kt
Labels: 🔨 Refactor
